---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fxa-browserid-verifier
  description: Verifies BrowserID assertions.
  tags:
    - typescript
    - javascript
    - node
    - hapi
  annotations:
    sentry.io/project-slug: mozilla/fxa-browserid-verify
    circleci.com/project-slug: github/mozilla/fxa
spec:
  type: service
  lifecycle: production
  owner: fxa-devs
  system: mozilla-accounts
