# Upload files in assets/product-icons & assets/legal to S3 buckets for CDN distribution
#
# Requirements:
# This action requires a set of AWS credentials with write access to the destination bucket directories (product-icons & legal)
#
#   Credentials must be passed in as the following secrets:
#    - CDN_S3_AWS_ACCESS_KEY_ID
#    - CDN_S3_AWS_SECRET_ACCESS_KEY

name: "Asset Upload"
on:
  push:
    branches:
      - main
    paths:
      - 'assets/**/'
      - '!assets/other/**'

jobs:
  Upload-assets-to-CDN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  "Asset upload to CDN"
        run: |
          aws s3 cp --cache-control 'public,max-age=86400' --recursive assets/product-icons s3://fxa-content-cdn-prod-distbucket-gqg70i8xqycy/product-icons
          aws s3 cp --cache-control 'public,max-age=86400' --content-disposition attachment --recursive assets/legal s3://fxa-content-cdn-prod-distbucket-gqg70i8xqycy/legal
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CDN_S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_S3_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
